# Generated by Django 5.0.13 on 2025-08-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Script', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Script')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Quảng cáo',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link video'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề'),
        ),
    ]
