# Generated by Django 5.0.13 on 2025-08-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0002_ads_product_link_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='Count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số'),
        ),
    ]
