# Generated by Django 5.0.13 on 2025-08-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0003_ads_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
