# Generated by Django 5.0.13 on 2025-08-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0004_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Link',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Link video'),
        ),
    ]
