# Generated by Django 5.0.13 on 2025-08-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0005_alter_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Iframe',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Iframe video'),
        ),
    ]
