# Generated by Django 5.2.7 on 2026-01-07 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleekweb", "0007_content_copylog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"ordering": ["-id"], "verbose_name_plural": "Nội dung"},
        ),
        migrations.RemoveField(
            model_name="content",
            name="content",
        ),
        migrations.AddField(
            model_name="content",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="content",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tiêu đề"
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời gian tạo"),
        ),
        migrations.CreateModel(
            name="ContentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line", models.TextField(verbose_name="Nội dung dòng")),
                ("order", models.IntegerField(default=0, verbose_name="Thứ tự")),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sleekweb.content",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "indexes": [
                    models.Index(
                        fields=["content", "order"],
                        name="sleekweb_co_content_05317b_idx",
                    )
                ],
            },
        ),
    ]
