# Generated by Django 5.2.7 on 2026-01-07 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleekweb", "0008_alter_content_options_remove_content_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="copylog",
            name="content_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copy_logs",
                to="sleekweb.contentline",
            ),
        ),
        migrations.AddIndex(
            model_name="copylog",
            index=models.Index(
                fields=["content_line", "copied_at"],
                name="sleekweb_co_content_379b29_idx",
            ),
        ),
    ]
