# Generated by Django 5.2.7 on 2026-01-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleekweb", "0009_copylog_content_line_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Slug",
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
